### ISSUE TITLE
In Docker, cli installs anew each time when executing the npx command in the Docker shell

### ISSUE THREAD

**Issue by rowild** [directus-community/directus-template-cli#33]
I try to use the directus template cli on a locally installed Docker instance (URL: http://localhist:8066/). As far as I know, in order to install the tempalte cli, I first have to switch to Docker's internal shell like this:

`docker exec -it directus-agency-tmpl-be-directus-1 sh`

Then I can execute

`npx directus-template-cli apply`

which first downloads the cli and then starts the prompts. 

Two problems happen:
1. Whenever I re-enter the Docker shell (`docker exec -it ...`) and run `npx directus-template-cli appy`, the cli is installed _again_. This happens every time when re-entering the shell and executing the npx command. I would expect that the project remembers that the cli was already downloaded. Why is this not the case?
2. The prompt asking for the admin token tells me that the token is wrong. I change the token, add the new one, and again I am told that the token is wrong.

The whole process in the Docker shell:

![Screenshot 2023-09-20 at 16 14 41](https://github.com/directus-community/directus-template-cli/assets/213803/6888a9a2-eb28-4d0d-97e3-cf8daeb1751b)

Create new admin token

![02-create-new-token](https://github.com/directus-community/directus-template-cli/assets/213803/71fc2574-9ce4-4e96-b378-9c6ec8fa8a97)

Apply new admin token

![03-add-new-token](https://github.com/directus-community/directus-template-cli/assets/213803/b1e27135-7c13-4ff3-bb99-ca987be6b8bd)

**Comment by rowild** [comment]
Well... I just found out that I have to apply the internal Docker port... I actually provided a PR to make that clearer in the Docu, but that one has not yet been merged. Any chance to do that?

**Comment by bryantgillespie** [comment]
As long as you're exposing the port for your Directus instance, I don't believe you actually need to run this within the Docker shell. You should just be able to run it within the terminal.

**Comment by joggienl** [comment]
The cli is agnostic, you do not have to run it inside the container. The `directus-template-cli` can also be used against a project that is hosted on Directus Cloud or any other live instance for that matter.
